export const ingredientsList = [
    'Rum',
    "Red Wine",
    "Gin",
    "Vodka",
    "Whiskey",
    "Tequila",
    "Bourbon",
    "Champagne",
    "Sweet Vermouth",
    "Scotch",
    "Lemon",
    "Orange",
    "Apple Cider",
    "Grape Juice",
    "Egg",
    "Chocolate",
    "Brandy",
    "Light Rum",
    "Coffee"
]