export const ingredientsList = [
    'Rum',
    "Red Wine",
    "Gin",
    "Vodka",
    "Whiskey",
    "Tequila",
    "Bourbon",
    "Champagne",
    "Sweet Vermouth",
    "Scotch",
    "Lemon",
    "Orange",
    "Apple Cider",
    "Grape Juice",
    "Egg",
    "Triple sec",
    "Brandy",
    "Light Rum",
    "Coffee",
    "Dry Vermouth",
    "Dark rum",
    "Amaretto",
    "Tea",
    "Apricot brandy",
    "Southern Comfort",
    "Johnnie Walker"
]